#!/bin/bash

set -eo pipefail

if [[ -z "$GCLOUD_ZONE" ]]; then
  echo "Set the GCLOUD_ZONE env variable."
  exit 1
fi

if [[ -z "$GCLOUD_CLUSTER" ]]; then
  echo "Set the GCLOUD_CLUSTER env variable."
  exit 1
fi

if [[ -z "$GCLOUD_PROJECT" ]]; then
  echo "Set the CLOUD_PROJECT env variable."
  exit 1
fi

if [[ -z "$GITHUB_TOKEN" ]]; then
	echo "Set the GITHUB_TOKEN env variable."
	exit 1
fi

if [[ -z "$GITHUB_REPOSITORY" ]]; then
	echo "Set the GITHUB_REPOSITORY env variable."
	exit 1
fi

if [[ -z "$REPO_TYPE" ]]; then
	echo "Set the REPO_TYPE env variable. Either FRONTEND or BACKEND. It is needed to build the helm chart name"
	exit 1
fi

URI=https://api.github.com
API_VERSION=v3
API_HEADER="Accept: application/vnd.github.${API_VERSION}+json"
AUTH_HEADER="Authorization: token ${GITHUB_TOKEN}"

main() {
    echo "Start Main"
    # Get all necessary vars from GITHUB_EVENT_PATH json
    REF=$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH")
    ACTION=$(jq --raw-output .action "$GITHUB_EVENT_PATH")
    PR_NR=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
    REPO=$(jq --raw-output .repository.name "$GITHUB_EVENT_PATH")
    OWNER=$(jq --raw-output .pull_request.head.repo.owner.login "$GITHUB_EVENT_PATH")
    MERGE=$(jq --raw-output .pull_request.merged "$GITHUB_EVENT_PATH")
    
    # build chart name for frontend repos
    CHART_NAME="rv-md1-$PR_NR-$REPO"
    if [[ "$REPO_TYPE" == "FRONTEND" ]]; then 
      CHART_NAME="pr-$PR_NR-$REPO"
    fi
    
	  echo "DEBUG -> action: $ACTION merged: $MAERGED chart_name: $CHART_NAME"
    if [[ "$ACTION" == "closed" ]]; then 
      echo "Remove helm chart: $CHART_NAME"
      # Login Gcloud
      gcloud container clusters get-credentials $GCLOUD_CLUSTER --zone $GCLOUD_ZONE --project $GCLOUD_PROJECT
      # Delete helm chart which then also deletes all pods services etc
      helm delete $CHART_NAME --purge
      
      # Delete Branch
      if [[ "$MERGED" == "true" && "$REF" != "master" ]]; then 
        echo "Deleting branch ref $REF for owner ${OWNER}/${REPO}..."
        curl -XDELETE -sSL \
        -H "${AUTH_HEADER}" \
        -H "${API_HEADER}" \
        "${URI}/repos/${OWNER}/${REPO}/git/refs/heads/${REF}"
      fi
    fi
}

main "$@"